export const API_CALL_REQUEST = 'API_CALL_REQUEST';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';
export const UPDATE_TOOLTIP = 'UPDATE_TOOLTIP';
export const SHOW_MODAL_UPDATE_TOOLTIP = 'SHOW_MODAL_UPDATE_TOOLTIP';
export const HIDE_MODAL_UPDATE_TOOLTIP = 'HIDE_MODAL_UPDATE_TOOLTIP';
